config/routes.rb
Rails.application.routes.draw do
resources :characters
resources :books 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/character.rb
class Character < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all 
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  def index
    @characters = Character.all
  end

  def show
    @character = Character.find(params[:id])
  end

  def new
    @character = Character.new 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/characterss_helper.rb
module CharacterssHelper
end

app/views/books/index.html.erb
<h1> Books </h1>
<% @books.each do |book| %>
    <h2><%= book.title %></h2>
    <%= link_to "Show Book", book_path(book) %>
<% end %> 

app/views/books/new.html.erb
<h1>New Books </h1>
<%= form_for @book do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :author %>
  <%= f.text_field :author %>

  <%= f.label :artist %>
  <%= f.text_field :artist %>

  <%= f.label :volume %>
  <%= f.text_field :volume %> 

  <%= f.submit %>
<% end %>

app/views/books/show.html.erb
<h1><%= @book.title %></h1>
<h4><%= @book.author %></h4>
<h4><%= @book.artist %></h4>
<h4><%= @book.volume %></h4> 
<%= link_to "Back", books_path %> 

app/views/characters/index.html.erb
<h1> Characters </h1>
<% @characters.each do |character| %>
    <h2><%= character.secretIdentity %></h2>
    <%= link_to "Show Character", character_path(character) %>
<% end %> 

app/views/characters/new.html.erb
<h1>New Character</h1>
<%= form_for @character do |f| %>
  <%= f.label :secretIdentity %>
  <%= f.text_field :secretIdentity %>

  <%= f.label :realName %>
  <%= f.text_field :realName %>

  <%= f.submit %>
<% end %>

app/views/characters/show.html.erb
<h1><%= @character.secretIdentity %></h1>
<h4><%= @character.realName %></h4>
<%= link_to "Back", characters_path %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ComicBook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>